// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD99N9VJq21xXAA9grbm8qKONyV8Ara6LM',
    appId: '1:628120438123:web:b898887f84e3c61b0e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    authDomain: 'rentit-11660.firebaseapp.com',
    storageBucket: 'rentit-11660.appspot.com',
    measurementId: 'G-QGKKTKTJ85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fQ582rs5uaN9sON8aYgBc9jraCD5WAY',
    appId: '1:628120438123:android:4bf7ecc3f949e6ed0e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    storageBucket: 'rentit-11660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAga4ikF-SOWWBAtSq52xXVdTr5UdGjamo',
    appId: '1:628120438123:ios:f0b277f820aee4490e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    storageBucket: 'rentit-11660.appspot.com',
    androidClientId: '628120438123-p8i7kc48p905uo401j0bmpfov2ue70b9.apps.googleusercontent.com',
    iosClientId: '628120438123-32bt5lahuf755b5l2281rhhbka21p7eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentItAdminWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAga4ikF-SOWWBAtSq52xXVdTr5UdGjamo',
    appId: '1:628120438123:ios:f0b277f820aee4490e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    storageBucket: 'rentit-11660.appspot.com',
    androidClientId: '628120438123-p8i7kc48p905uo401j0bmpfov2ue70b9.apps.googleusercontent.com',
    iosClientId: '628120438123-32bt5lahuf755b5l2281rhhbka21p7eu.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentItAdminWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD99N9VJq21xXAA9grbm8qKONyV8Ara6LM',
    appId: '1:628120438123:web:eb0db3513ff518a00e782e',
    messagingSenderId: '628120438123',
    projectId: 'rentit-11660',
    authDomain: 'rentit-11660.firebaseapp.com',
    storageBucket: 'rentit-11660.appspot.com',
    measurementId: 'G-GQKE9MQNG3',
  );
}
